modules: lvgl: fix multiple LVGL inputs
The LVGL input callback does not use an instance specific name, so we
can only ever have one instance of this type. This issue was evident by
a build error, e.g., when using "zephyr,lvgl-keypad-input" nodes twice:

  error: redefinition of '_input_callback__lvgl_keypad_process_event'

(cherry picked from commit 5bcb5242ed352f05b870d290c97c4388586064d1)

Original-Signed-off-by: Gero Schwäricke <gero.schwaericke@posteo.de>
GitOrigin-RevId: 5bcb5242ed352f05b870d290c97c4388586064d1
Cr-Build-Id: 8735286451693989857
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735286451693989857
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I5fc5727f3a4749bfd6858477c71b1f869fe5b413
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5901538
Tested-by: Al Semjonovs <asemjonovs@google.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>