Bluetooth: host: Fix scan info dangling pointer
Clear pointer to the le_adv_recv() stack frame before returning to the
calling function. This fixes a potential compiler warning newer gcc
versions.

zephyr/subsys/bluetooth/host/scan.c: In function ‘le_adv_recv’:
zephyr/subsys/bluetooth/host/scan.c:463:20: error: storing the address
of local variable ‘id_addr’ in ‘*info.addr’ [-Werror=dangling-pointer=]
  463 |         info->addr = &id_addr;
      |         ~~~~~~~~~~~^~~~~~~~~~
zephyr/subsys/bluetooth/host/scan.c:439:22: note: ‘id_addr’ declared here
  439 |         bt_addr_le_t id_addr;
      |                      ^~~~~~~

Fixes #48459

(cherry picked from commit 7ebaf1b10b9a584e8f9d7529407b495766684bfe)

Original-Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>
GitOrigin-RevId: 7ebaf1b10b9a584e8f9d7529407b495766684bfe
Change-Id: I7289c3940f4a3a09f7ce0a75d2521ea6a5f76980
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3814823
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: Fabio Baltieri <fabiobaltieri@google.com>