Devicetree: edtlib: fix possible AttributeError in Property.description
Attempting to access the property Property.description
when Property.spec.description is None would raise

Known properties that may not have a description
(Property.spec.description is None):
- 'compatible' for nodes such as / /soc /soc/timer@e000e010 /leds /pwmleds
- 'reg'        for nodes such as /soc/timer@e000e010
- 'status'     for nodes such as /soc/timer@e000e010
- 'gpios'      for nodes such as /leds/led_0 /buttons/button_0
- 'pwms'       for nodes such as /pwmleds/pwm_led_0

This patch checks the PropertySpec.description attribute before calling
strip(): will return None, and not raise AttributeError.

(cherry picked from commit 230c80e0009f23edd5f0fc477c80df760a3d5590)

Original-AttributeError: 'NoneType' object has no attribute 'strip'.
Original-Signed-off-by: Chris Duf <chris@openmarl.org>
Original-Co-authored-by: Gerard Marull-Paretas <gerard@teslabs.com>
GitOrigin-RevId: 230c80e0009f23edd5f0fc477c80df760a3d5590
Change-Id: I1ae46a54dc7ea268d5df85590ff01646239c098f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3952474
Tested-by: Keith Short <keithshort@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>