scripts: twisterlib: Fix --short-build-path argument handling
When `--short-build-path` argument is specified to the twister, the
following error message is displayed because the Python argparse module
does not allow specifying a mutually exclusive argument as required:

  ValueError: mutually exclusive arguments must be optional

This commit removes the `required` parameter when adding the `--ninja`
argument, which is a mutually exclusive argument, and adds a manual
check to validate this condition instead.

(cherry picked from commit 1f81d2cd978ccdb6161412b3f16bc6e47bef49b8)

Original-Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
GitOrigin-RevId: 1f81d2cd978ccdb6161412b3f16bc6e47bef49b8
Change-Id: I1c14c05a8369f4b9229d9aa354859b28fe0bf5ee
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3788476
Tested-by: Al Semjonovs <asemjonovs@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>