tests: lib: cmsis_nn: Initialise bias dimensions for depthwise convolve
This commit adds an initialisation for the `bias_dims` variable, which
is given as an input to the `arm_depthwise_conv_s8` function.

Note that the `bias_dims` parameter is currently unused by the function
implementation.

This fixes the following warning reported by the GCC 12:

  error: 'bias_dims' may be used uninitialized
  Werror=maybe-uninitialized]

(cherry picked from commit 8355341c66fb1cbe5466e47ef31ed26613d2f59b)

Original-Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
GitOrigin-RevId: 8355341c66fb1cbe5466e47ef31ed26613d2f59b
Change-Id: Idf6b7c419b792e3ae7bf57c155d7016800fd9283
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3823367
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>