drivers: serial: pl011: Fix ignored const qualifiers
When trying to build Zephyr with -Wignored-qualifiers this leads to a
compiler warning like:

zephyr/drivers/serial/uart_pl011_registers.h:40:1: error: type
qualifiers ignored on function return type [-Werror=ignored-qualifiers]

Since the return value is copied by the caller, making it const has no
effect and the compiler warns that this is being ignored. This enables
applications to build with additional compiler warnings turned on.

(cherry picked from commit 47a0813561afb06ba6b681dfcd4d2224847e3962)

Original-Signed-off-by: Benjamin Gwin <bgwin@google.com>
GitOrigin-RevId: 47a0813561afb06ba6b681dfcd4d2224847e3962
Cr-Build-Id: 8739725789595072145
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8739725789595072145
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Id52014024c9503a400179cf4fb0054cc9687208d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5786055
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>