boards: beagle_bcf: Fix undefined references to pinctrl and gpio device
This patch fixes undefined references when compiling tests/drivers/flash
for beagleconnect_freedom board using following command:

west build -b beagleconnect_freedom tests/drivers/flash

Adding CONFIG_PINCTRL fixes undefined references to
'pinctrl_lookup_state' and 'pinctrl_configure_pins'.

Adding CONFIG_GPIO fixes undefined reference to '__device_dts_ord_13'
from spi_nor and spi_cc13xx_cc26xx drivers.

Fixes #56181

(cherry picked from commit 5ec4aaff5c676841dc1932096bd0606435fb0c26)

Original-Signed-off-by: Patryk Duda <pdk@semihalf.com>
GitOrigin-RevId: 5ec4aaff5c676841dc1932096bd0606435fb0c26
Change-Id: I25a749b4cb7956cbcd652f58976d75f7844e97a2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4377019
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>