tests: kernel: Fix address-of-packed-mem warning
The warning below appears once -Waddress-of-packed-mem is enabled:

/__w/zephyr/zephyr/tests/kernel/mem_protect/userspace/src/main.c: In
function 'test_main':
/__w/zephyr/zephyr/tests/kernel/mem_protect/userspace/src/main.c:1024:17:
z_thread_stack_element'} pointer (alignment 1) to a 'struct
z_x86_thread_stack_header' pointer (alignment 4096) may result in an
unaligned pointer value [-Werror=address-of-packed-member]
 1024 |  hdr = ((struct z_x86_thread_stack_header *)ztest_thread_stack);

To avoid the warning, use an intermediate void * variable.

More info in #16587.

(cherry picked from commit cfbaac6733b4186f2129e1c438c324a6736e2daf)

error: converting a packed 'k_thread_stack_t' {aka 'struct
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
GitOrigin-RevId: cfbaac6733b4186f2129e1c438c324a6736e2daf
Change-Id: I6bec4c0dbe3f5f99973533c83d5e2b649a477b23
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3332180
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>