sensors: default_rtio_sensor: fix build warning
Fix a build warning on 64 bit architectures:

zephyr/drivers/sensor/default_rtio_sensor.c:238:17: error: format '%zu'
expects argument of type 'size_t', but argument 2 has type 'uint32_t'
{aka 'unsigned int'}

num_channels type changed to uint32_t in 96175fcc47.

(cherry picked from commit d53b1a1c0efcd784239d5a73eefd25a62ced6f30)

Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: d53b1a1c0efcd784239d5a73eefd25a62ced6f30
Change-Id: I8e020edf97b70806ef622ded89f9f30098664860
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4921895
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Keith Short <keithshort@chromium.org>
Tested-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>