MAINTAINERS: fix missing ":"
Add a missing ":" for "Drivers: Regulators", currently causing PR
assigner failure:

```
yaml.scanner.ScannerError: while scanning a simple key
  in "MAINTAINERS.yml", line 976, column 1
could not find expected ':'
  in "MAINTAINERS.yml", line 977, column 3
```

(cherry picked from commit 06e518265ccf7f9c4534b9e6dc0e85579a009432)

Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 06e518265ccf7f9c4534b9e6dc0e85579a009432
Change-Id: I6101fdad4901946b52b2d5325a64e830ca7fc329
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4126993
Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>