bluetooth: tester: vcp: Remove unused include
Fixes build error:
mesh/keys.h:40:2: error: #error "Crypto library has not been chosen"

(cherry picked from commit 76dc5d37cb136fea15e84a5cdd3c59cc84763784)

Original-Signed-off-by: Magdalena Kasenberg <magdalena.kasenberg@codecoup.pl>
GitOrigin-RevId: 76dc5d37cb136fea15e84a5cdd3c59cc84763784
Change-Id: I1b1ab030521adc333c698d9457e0d82cb0f16a05
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4649631
Reviewed-by: Keith Short <keithshort@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Commit-Queue: Keith Short <keithshort@chromium.org>
Tested-by: Keith Short <keithshort@chromium.org>