Bluetooth: audio: lc3: Fix build error
This fixes build error caused by redundant comma without expression
lc3.h:269:74: error: expected expression before ',' token
  269 |          (_max_frames_per_sdu)))),                         \
      |

(cherry picked from commit 0197d1154ae3b6833295e701e8297b42574bbe17)

Original-Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>
GitOrigin-RevId: 0197d1154ae3b6833295e701e8297b42574bbe17
Change-Id: Id315dd42bf7131b7abdc86a945736d994cd3c026
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4836001
Commit-Queue: Keith Short <keithshort@chromium.org>
Reviewed-by: Keith Short <keithshort@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: Keith Short <keithshort@chromium.org>