drivers: display: gd7965: fix build break
gd7965 broke after 42bbb30ecf:

/zephyr/drivers/display/gd7965.c: In function 'gd7965_init':
/zephyr/drivers/display/gd7965.c:379:23: error: passing argument 1 of
'device_is_ready' from incompatible pointer type
[-Werror=incompatible-pointer-types]
  379 |  if (!device_is_ready(&config->reset_gpio.port)) {
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
      |                       |
      |                       const struct device * const*

Fix all the occurrences.

(cherry picked from commit 1b370eead8541bd4c1808ad287456ef54d3aca35)

Signed-off-by: Fabio Baltieri <fabio.baltieri@gmail.com>
GitOrigin-RevId: 1b370eead8541bd4c1808ad287456ef54d3aca35
Change-Id: If1bb4a99dcc5f51e4edaaf33fad104863c328e7b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3490965
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Aaron Massey <aaronmassey@google.com>
Commit-Queue: Aaron Massey <aaronmassey@google.com>
Tested-by: Aaron Massey <aaronmassey@google.com>