net: Fix macro for XCC
NET_SOCKET_GET_NAME macro adds some extra parenthesis that, on XCC (based
on GCC 4.2) ends up in the generated assembly, thus causing `as` to error

  Error: junk at end of line, first unrecognized character is `('

It appears that the parenthesis are actually concatenated to the
generated name for identifier. This patch just removes them.

(cherry picked from commit 827d07abbcd56b27eef89ac4921fadcbb1fcbd35)

with:
Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>
GitOrigin-RevId: 827d07abbcd56b27eef89ac4921fadcbb1fcbd35
Change-Id: Ic05c48e652b311696ef4ae1fef7d66394e61d6dc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3480399
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Reviewed-by: Aaron Massey <aaronmassey@google.com>
Tested-by: Aaron Massey <aaronmassey@google.com>
Commit-Queue: Aaron Massey <aaronmassey@google.com>