Bluetooth: Mesh: Fix compiler warning
When building with an LLVM toolchain get the following warning:

bluetooth/mesh/pb_adv.c:774:4: error: expression which evaluates to zero
treated as a null pointer constant of type
'void *' [-Werror,-Wnon-literal-null-conversion]
                        PROV_BEARER_LINK_STATUS_SUCCESS);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix by adding a cast to (void *).

(cherry picked from commit 0342deb5d930b59b3d15fa84256ecd3ed4643c76)

Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
GitOrigin-RevId: 0342deb5d930b59b3d15fa84256ecd3ed4643c76
Change-Id: I54fc7a4be5e860c3b2536e9a721736dcbe4e16c1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4345340
Reviewed-by: Keith Short <keithshort@chromium.org>
Tested-by: Keith Short <keithshort@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Commit-Queue: Keith Short <keithshort@chromium.org>