linker: ld: lld: do not do RELRO when using llvm/clang
GNU ld and LLVM lld both complain under C++:
  error: section: init_array is not contiguous with other relro sections

So do not create RELRO program header.

(cherry picked from commit 5d9079ba6d2758f3f48ac4adc9d3cfd0b1aa97fa)

Original-Signed-off-by: Daniel Leung <daniel.leung@intel.com>
GitOrigin-RevId: 5d9079ba6d2758f3f48ac4adc9d3cfd0b1aa97fa
Change-Id: Id7fb28dd0607a2a0976941080beef72dd83cf427
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4384640
Tested-by: Al Semjonovs <asemjonovs@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>