drivers: dma: Remove double parentheses in if statements
This patch fixes following compilation error when compiling using clang

drivers/dma/dma_stm32.c:364:42: error: equality comparison with
extraneous parentheses [-Werror,-Wparentheses-equality]
        if ((config->head_block->source_address == 0)) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
drivers/dma/dma_stm32.c:364:42: note: remove extraneous parentheses
around the comparison to silence this warning
        if ((config->head_block->source_address == 0)) {
            ~                                   ^   ~

(cherry picked from commit c0e1c5e09b4e0b9bc05b7878942e0e126ad5f2af)

Original-Signed-off-by: Patryk Duda <pdk@semihalf.com>
GitOrigin-RevId: c0e1c5e09b4e0b9bc05b7878942e0e126ad5f2af
Change-Id: Iee89fda8184d8f71907bb554dbac827ef7fd1e05
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4579210
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>