net: lwm2m: device object: Fix coverage compatibility
Starting with b1d24e425c3a30cdf1aed3c54c25a2518061accc (net: lwm2m:
device object: optionally store error list in settings), it was no
longer possible to build the code with coverage enabled when the
settings subsystem was disabled.

The build would fail with an error like this:

> subsys/net/lib/lwm2m/lwm2m_obj_device.c:262: undefined reference to
> `settings_name_steq'

This fixes #70923.

(cherry picked from commit ccc58b8ce54505e11eee28914dac1821143b6b98)

Original-Signed-off-by: Reto Schneider <reto.schneider@husqvarnagroup.com>
GitOrigin-RevId: ccc58b8ce54505e11eee28914dac1821143b6b98
Change-Id: I6acefdaf9cddcdd9cc5ca61211adb876b6722b5e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5423735
Tested-by: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>