samples: big_http_download: make num_iterations unsigned
It is documented as unsigned in
samples/net/sockets/big_http_download/Kconfig

Signed overflow is undefined behavior, unsigned is not. This fixes the
following warning:

   -Wstrict-overflow=1

samples/net/sockets/big_http_download/src/big_http_download.c:346:2:
In function 'main':
                           [-Werror=aggressive-loop-optimizations]
  346 |  } while (--num_iterations != 0);

(cherry picked from commit f38c6b67ed16446c068a1cabe2f2cfbc09d57ebb)

error: iteration 2147483648 invokes undefined behavior
Signed-off-by: Marc Herbert <marc.herbert@intel.com>
GitOrigin-RevId: f38c6b67ed16446c068a1cabe2f2cfbc09d57ebb
Change-Id: I18b6ebf5bd8276fa2fd5721e8174d7e611d39d29
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3370024
Reviewed-by: Aaron Massey <aaronmassey@google.com>
Commit-Queue: Aaron Massey <aaronmassey@google.com>
Tested-by: Aaron Massey <aaronmassey@google.com>