zbus: add MULTITHREADING dependency
Zbus uses mutexes internally that are available
only when MULTITHREADING is enabled so add
it to fix the following error:

/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/
12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/subsys/
zbus/libsubsys__zbus.a(zbus.c.obj): in function `k_mutex_init':
/builds/zephyr/mcuboot/zephyr/include/generated/syscalls/kernel.h:969:
undefined reference to `z_impl_k_mutex_init'

(cherry picked from commit 43d5f392090dd5060d056a527917312bef913864)

Original-Signed-off-by: Bartosz Bilas <b.bilas@grinn-global.com>
GitOrigin-RevId: 43d5f392090dd5060d056a527917312bef913864
Change-Id: Ib409715118b81e9ba9438cd3a3564292cf764513
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5057233
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>