samples: net: Disable native_posix target in samples
The native_posix compilations fail with various socket
errors like this:

samples/net/sockets/echo_server/src/udp.c:45:26: error: implicit \
 declaration of function ‘socket’ [-Werror=implicit-function-declaration]
 45 |         data->udp.sock = socket(bind_addr->sa_family, SOCK_DGRAM,
    |                                 IPPROTO_UDP);

Disable the native_posix board from networking samples so that CI can pass.

(cherry picked from commit b8fc1c4c3e0b2bbf0a6403c185a60db104b900a3)

Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
GitOrigin-RevId: b8fc1c4c3e0b2bbf0a6403c185a60db104b900a3
Change-Id: I5feb7ab422ed48c0380cc31ea269414933aeded0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5427359
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: Tristan Honscheid <honscheid@google.com>