Bluetooth: OTC: Use OTS defines and types instead of separate ones
Update the Object Transfer Client to use OTS defines and types instead
of the ones left over from the previous "le-audio local" object
transfer service:
DIR_LIST, object ID size, OACP and OLCP

Remove the no longer used defines and types from the OTC header file.
moved to the olcp internal header file, for expected later use.

(cherry picked from commit 1a81bceea2e952c50643001485fe32c6c03ed376)

Exception: The OLCP sort order defines have not been removed, but
Signed-off-by: Asbjørn Sæbø <asbjorn.sabo@nordicsemi.no>
GitOrigin-RevId: 1a81bceea2e952c50643001485fe32c6c03ed376
Change-Id: I5d9a6dd552c8f49f1ce2fc5c9f358ab44095597b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3506705
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: Al Semjonovs <asemjonovs@google.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>