tests: work_queue: initialize msg
Make sure msg is initialized before being used, fixes compiler warning:

  main.c:735:9: error: 'msg' may be used uninitialized

(cherry picked from commit 7c231e3e271ab0525bbbf938dbab739b5a3bd274)

Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 7c231e3e271ab0525bbbf938dbab739b5a3bd274
Change-Id: I35bbf534defe070dfb3b3573265006b6edb54844
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3907809
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>