debug: coredump: Fix build issue with armclang
Building tests/drivers/coredump/coredump_api with armclang gets:

include/zephyr/debug/coredump.h:98:2: error: unknown type name 'uint8_t'
        uint8_t *buffer;
        ^

Fix simply be including <stdint.h> to get uint8_t typedef.

(cherry picked from commit b0ea0c8ec6135aa5cb8d0e70ca72af2abe1f38fa)

Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
GitOrigin-RevId: b0ea0c8ec6135aa5cb8d0e70ca72af2abe1f38fa
Change-Id: I066acc930369e4d86eaad004249f2a893b88b6a9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4350068
Reviewed-by: Aaron Massey <aaronmassey@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>