modem: wncm14a2a: fix warning with isalpha/isdigit
When building with arm-clang we get warnings of the type:

wncm14a2a.c:828:14: error: array subscript is of type
			   'char' [-Werror,-Wchar-subscripts]:
                } else if (isalpha(c2) != 0) {
                           ^~~~~~~~~~~

Fix this by adding explicit casts to (int) when callinng isalpha()
or isdigit().

(cherry picked from commit 1a5d47ef6d898707b0eac19b277084ccd6f81756)

Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
GitOrigin-RevId: 1a5d47ef6d898707b0eac19b277084ccd6f81756
Change-Id: Id1d41e39d6edd975f6e44ee26313adba5a043e87
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4474962
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>