net: ipv6: use static inlines where it makes sense for stubs
If we're disabling certain features and instead providing function stubs,
it doesn't make sense to use macros for those routines that return values
that the user may check unless we want to provide them with vague errors
like:

src/coap-server.c:101:55: error: expected expression before ';' token
  101 |  ret = net_ipv6_mld_join(iface, &mcast_addr.sin6_addr);

When a function we're mocking up returns a value, use a static inline
stub.

(cherry picked from commit 7cddc5a6a3301f092fb602ef28b5b2e91c9ceec3)

Original-Signed-off-by: Bartosz Golaszewski <bartosz.golaszewski@huawei.com>
GitOrigin-RevId: 7cddc5a6a3301f092fb602ef28b5b2e91c9ceec3
Change-Id: I9ce3b0a473c501d0bbe965e1c8c5da243cd78dae
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3791123
Tested-by: Al Semjonovs <asemjonovs@google.com>
Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>