Bluetooth: Controller: Fix build for hci_uart sample with new LLCP
ull_tx_queue.h needs to be included before ll_sw/ull_conn_types.h

zephyr/zephyr/subsys/bluetooth/controller/hci/hci.c
In file included from zephyr/zephyr/subsys/bluetooth/controller/
    hci/hci.c:52:
../../subsys/bluetooth/controller/./ll_sw/ull_conn_types.h:453:18:
     error: field 'tx_q' has incomplete type
  453 |  struct ull_tx_q tx_q;
      |                  ^~~~

(cherry picked from commit 1f5417988939d6ed80775b46b550c4a79b84aca2)

Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>
GitOrigin-RevId: 1f5417988939d6ed80775b46b550c4a79b84aca2
Change-Id: Id3ee2cd1fdf4aa04b83ad9950f05d8da53d60a20
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3308756
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Reviewed-by: Yuval Peress <peress@google.com>
Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>