tests: interrupt: Fix armclang compiler warning
When building this test with the armclang compiler we get the following
warning:

tests/kernel/interrupt/src/dynamic_isr.c
tests/kernel/interrupt/src/dynamic_isr.c:23:32: error: 'used' attribute
ignored on a non-definition declaration [-Werror,-Wignored-attributes]

extern struct _isr_table_entry __sw_isr_table _sw_isr_table[];
                               ^
There is no need to add the __sw_isr_table on the extern, so remove it
to address the warning.

(cherry picked from commit 99fee43f077b69cb735f81c843a9ea2d434a5e0f)

Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
GitOrigin-RevId: 99fee43f077b69cb735f81c843a9ea2d434a5e0f
Change-Id: I9590f9785314a71d6c00f93f29daba4817dc4853
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4414157
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Yuval Peress <peress@google.com>
Commit-Queue: Yuval Peress <peress@google.com>
Tested-by: Yuval Peress <peress@google.com>