fix: lvgl: modules: keypad input log module
Compilation error "undefined reference to log_const_lvgl"
happened in lvgl_keypad_input.c when trying to get logs with
lvgl keypad module. Fixed by adding log level parameter
in log module macro.

(cherry picked from commit 97fce09392053862b3d823f262e6bb15596ca036)

Original-Signed-off-by: Eve Redero <eve.redero@gmail.com>
GitOrigin-RevId: 97fce09392053862b3d823f262e6bb15596ca036
Change-Id: I271fbe0d664f0adc3c9d7240d575c0c6b2b1da0b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5288871
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>