drivers: input: Fix uninitialized closest_mv variable warning
Building with GCC 9.4.0 gives the following warning/error:

  error: closest_mv may be used uninitialized in this function

This commit fixes it.

(cherry picked from commit 35502592a7c702954697660f390b46e4912f8c56)

Original-Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>
GitOrigin-RevId: 35502592a7c702954697660f390b46e4912f8c56
Change-Id: I77671c8a9bdbcbf026837902c2e50b283ab16176
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5356021
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>