runners: jlink: Fix NoneType object error
The commit 221199e15b85a070b3d81709eee3d533c9f99967 presents a bug that
makes west flash failed with error.

In function is_tunnel(), tunnel may contain None and has no attribute
"startswith". Fix it.

(cherry picked from commit 829c03bcdca378fa2fa55484d16a190d379f754c)

Original-AttributeError: 'NoneType' object has no attribute 'startswith'
Original-Signed-off-by: Phi Bang Nguyen <phibang.nguyen@nxp.com>
GitOrigin-RevId: 829c03bcdca378fa2fa55484d16a190d379f754c
Cr-Build-Id: 8733565196572304993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8733565196572304993
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I6a6ed29d28c2dd114921af945b1efb7a5e7daf3a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5940417
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Commit-Queue: Eric Yilun Lin <yllin@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>