west: build.py: resolve symlinks in cached source directory check
Fixes the following error:

  dir in CMakeCache.txt>", but source directory "<resolved source dir>"
  was specified; please clean it, use --pristine, or use --build-dir to
  set another build directory
FATAL ERROR: refusing to proceed without --force due to above error

Fixes initial commit ab82264ace163 ("scripts: add west build, flash, and
debug commands")

(cherry picked from commit c2524a07a661828f0e7f65f58cece1023aa9a5d1)

ERROR: Build directory "<whatever>" is for application "<symbolic source
Signed-off-by: Marc Herbert <marc.herbert@intel.com>
GitOrigin-RevId: c2524a07a661828f0e7f65f58cece1023aa9a5d1
Change-Id: I59147b53950941d468783f9e306e0fa7db51fb32
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3274948
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>