doc: dts: add help for undefined reference to __device_dts_ord_N
This is an FAQ and we don't have a satisfactory page that describes
the current state of the world for how to troubleshoot. This leads
to frustrated users and duplicated support efforts. Try to improve
this by at least writing down what people have to do today.

If we ever improve the situation by adding a machine-readable map
between drivers, Kconfig options, and DT compatibles, we can hopefully
do better than this, but at least it's a start.

(cherry picked from commit c625a0e7a820245cf1dbd18dceb7b8a2847ace67)

Original-Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>
GitOrigin-RevId: c625a0e7a820245cf1dbd18dceb7b8a2847ace67
Change-Id: I0aa89d585aadd6f85711f7eeb72611b649108084
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4484081
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>