samples: subsys: ipc: Fix warning of `size_t` formatting with `%.*s`
This addresses the following warning building with `CONFIG_64BIT=y`:

    error: field precision specifier '.*' expects argument of type 'int',
    but argument X has type 'size_t' {aka 'long unsigned int'}

(cherry picked from commit bb94c63fa2447af60d449fc1234c0cbb288168d5)

Original-Signed-off-by: Chen Xingyu <hi@xingrz.me>
GitOrigin-RevId: bb94c63fa2447af60d449fc1234c0cbb288168d5
Cr-Build-Id: 8730286630880259329
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730286630880259329
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I04404dddd3760fadef5bf92e15acbcfb614a766d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6045627
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>