armclang: fix compiler warnings with isprint()
We get compile warnings of the form:

drivers/console/uart_console.c:508:8: error: converting the result of
'<<' to a boolean; did you mean
'((__aeabi_ctype_table_ + 1)[(byte)] << 28) != 0'?
 [-Werror,-Wint-in-bool-context]
                if (!isprint(byte)) {
                     ^

Since isprint returns an int, change check to an explicit test against
the return value.

(cherry picked from commit 831bd2f841faa49008c4acd471bb019f44de1c9d)

Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
GitOrigin-RevId: 831bd2f841faa49008c4acd471bb019f44de1c9d
Change-Id: I13ecd0e0c79e61012b348c5f88055f3d456a0873
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4350077
Reviewed-by: Aaron Massey <aaronmassey@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>