mbedtls: fix _mbedtls_init() invocation
SYS_INIT() requires pointer to function that takes `void` now, instead of
pointer to device structure. Since the commit was developed before that
switch, it still invoked it with NULL. Fix that now.

Fixes:

  zephyr/modules/mbedtls/zephyr_init.c: In function 'mbedtls_init':
  zephyr/modules/mbedtls/zephyr_init.c:108:16: error: too many arguments \
                                              to function '_mbedtls_init'
    108 |         return _mbedtls_init(NULL);
        |                ^~~~~~~~~~~~~
  zephyr/modules/mbedtls/zephyr_init.c:86:12: note: declared here
     86 | static int _mbedtls_init(void)
        |

(cherry picked from commit 630555d9f6ead7530b3d1e5a5fba96104607550c)

Original-Signed-off-by: Marcin Niestroj <m.niestroj@emb.dev>
GitOrigin-RevId: 630555d9f6ead7530b3d1e5a5fba96104607550c
Change-Id: Id96e0e76a4b91d556393805d34aca63656753932
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4670183
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>