toolchain: gcc: Fix separator between directives on same line
The Arm assembler in binutils 2.40 contains a change [1] which affects
how multiple directives on the same line are parsed.

Previously, the following combination of directives parsed successfully:

    .code 32 .balign 4

With binutils 2.40, the following error is now seen:

    Error: junk at end of line, first unrecognised character is `.'

To fix, insert a semicolon after '.code 32', as there already is after
'.thumb'.

[1] https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=a37854f9162fac592b669eda53f465fc190c9341

(cherry picked from commit 2f2f3edacdf13bb9bc0be1ce3b80726dce6fb1c0)

Original-Signed-off-by: Peter Hoyes <Peter.Hoyes@arm.com>
GitOrigin-RevId: 2f2f3edacdf13bb9bc0be1ce3b80726dce6fb1c0
Change-Id: I3e9119e6a820ab457da9962e137794b6639833c9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4446708
Reviewed-by: Keith Short <keithshort@chromium.org>
Tested-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>