nxp_adsp: linker: Fix _heap_sentry reference
Add _heap_sentry value to fix build errors for
newlib, like: "undefined reference to `_heap_sentry'"

(cherry picked from commit 9cac089f8c51b3c47b1b42bd0b99766f69b296db)

Original-Signed-off-by: Iuliana Prodan <iuliana.prodan@nxp.com>
GitOrigin-RevId: 9cac089f8c51b3c47b1b42bd0b99766f69b296db
Change-Id: I1ea4419cfeb80d9c434e056eb46a2f3973461a80
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5044059
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: Tristan Honscheid <honscheid@google.com>