riscv: linker.ld: Fix undefined reference linker error
The commit a28830b aligned the data and rename some symbols.  However
there are two symbols at riscv linker script that were missing, which
causes below linker error:

kernel/xip.c:28: undefined reference to `__itcm_load_start'
kernel/xip.c:43: undefined reference to `__dtcm_data_load_start'

Rename below symbols to fix the issues.

__itcm_rom_start -> __itcm_load_start
__dtcm_data_rom_start -> __dtcm_data_load_start

(cherry picked from commit 1212ea0c399ab6c029d91195333dd7815a53d0c1)

Signed-off-by: Gerson Fernando Budke <nandojve@gmail.com>
GitOrigin-RevId: 1212ea0c399ab6c029d91195333dd7815a53d0c1
Change-Id: I34923222fcb560f34bea11fc785567fc510c2ad3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3350681
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Aaron Massey <aaronmassey@google.com>
Commit-Queue: Aaron Massey <aaronmassey@google.com>