net: Fix build issues with arm-clang
The arm-clang compiler/linker does not optimize away unused function
symbols and thus will error if symbols that are referenced are not
defined.  To fix this add needed ifdef'ry.

Build various network samples that utilize ethernet but don't have
CONFIG_NET_PROMISCUOUS_MODE will get a link error for:

	Error: L6218E: Undefined symbol
	net_mgmt_NET_REQUEST_ETHERNET_SET_PROMISC_MODE
	(referred from ethernet.o).

Fix by adding ifdef protection around promisc code.

(cherry picked from commit 0090ad718a70af54a7a9d30cb02b1fe89ecf5e40)

Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
GitOrigin-RevId: 0090ad718a70af54a7a9d30cb02b1fe89ecf5e40
Change-Id: Id89d2dc78c66f4d91db0f92e951cf62bb2322759
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4479719
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>