net: websocket: fix undefined reference
Fix undefined reference to MSG_DONTWAIT while building websocket client.

(cherry picked from commit 4c16ec1fba56c5631fb0ab19583a8a30d7ded529)

Original-Signed-off-by: Joel Guittet <joelguittet@gmail.com>
GitOrigin-RevId: 4c16ec1fba56c5631fb0ab19583a8a30d7ded529
Cr-Build-Id: 8739001010820476625
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8739001010820476625
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I0c760987d5f8cec33e87f78de1c37eaf1ed33d80
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5803472
Reviewed-by: Eric Yilun Lin <yllin@google.com>
Tested-by: Eric Yilun Lin <yllin@google.com>
Commit-Queue: Eric Yilun Lin <yllin@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>