drivers: bbram: stm32: add include to fix compilation error
Driver BBRAM for STM32 had a compilation error: "unknown type name
'RTC_TypeDef'" due to missing include file.

(cherry picked from commit b0e1e9f5fbf7f6b1f42fcc643d0e3b232b871c65)

Original-Signed-off-by: Guillaume Gautier <guillaume.gautier-ext@st.com>
GitOrigin-RevId: b0e1e9f5fbf7f6b1f42fcc643d0e3b232b871c65
Change-Id: Id6f977355e848bee8cd0f93173a466e300b701ec
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5295751
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>