irq: Add extern define to _isr_wrapper
When CONFIG_GEN_IRQ_VECTOR_TABLE and CONFIG_GEN_SW_ISR_TABLE are enabled
the generate IRQ table is trying to reference the _isr_wrapper function.

Add an extern to that to avoid a failure when compiling and remove the
previous arch-specific declarations.

arch/common/isr_tables.c:48:38: error: '_isr_wrapper' undeclared here
				(not in a function)

(cherry picked from commit b55e6dbfce6060decb778bdacb17f9016ff081e0)

Original-Signed-off-by: Carlo Caione <ccaione@baylibre.com>
GitOrigin-RevId: b55e6dbfce6060decb778bdacb17f9016ff081e0
Change-Id: I83ae9490f70ddd993f2cf222653f11528fb7ab54
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3716554
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>