ITE drivers/kscan: support tests/driver/kscan/kscan_api
Add kscan0 to support tests/driver/kscan/kscan_api.

When running the tests code on it8xxx2_evb, it shows fatal
created and executed, the KSI interrupt will be enabled and
before we call irq_connect_dynamic(), so we switch both
function sequence.

(cherry picked from commit 336d0f67b33c5003d3005c32bfae6b6bf312e090)

error: IRQ is enabled. We find that once polling_task() is
Signed-off-by: Ruibin Chang <Ruibin.Chang@ite.com.tw>
GitOrigin-RevId: 336d0f67b33c5003d3005c32bfae6b6bf312e090
Change-Id: Ie813f0b5d228159d269034c4a472974b04155351
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3398553
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>
Tested-by: Tristan Honscheid <honscheid@google.com>